import { describe, it, expect, beforeEach } from "vitest";
import { autoInvoicesRouter } from "../server/routers/autoInvoices";
import { getDb } from "../server/db";
import { videoCallAttendance, sessions, projects, users, invoices } from "../drizzle/schema";
import { eq } from "drizzle-orm";

describe("Invoice Generation System", () => {
  const mockContext = {
    user: {
      id: 1,
      openId: "test-open-id",
      email: "test@example.com",
      name: "Test User",
      role: "team_member" as const,
      organizationId: 1,
      profileImageUrl: "",
      loginMethod: "oauth",
      canPostJobs: false,
      createdAt: new Date(),
      updatedAt: new Date(),
      lastSignedIn: new Date(),
        pushToken: null,
        notificationPreferences: null,
    },
    req: {} as any,
    res: {} as any,
  };

  it("should fetch draft invoice with unpaid activities", async () => {
    const caller = autoInvoicesRouter.createCaller(mockContext);
    
    const draftInvoice = await caller.getDraftInvoice();
    
    expect(draftInvoice).toBeDefined();
    expect(draftInvoice).toHaveProperty("activities");
    expect(draftInvoice).toHaveProperty("totalMinutes");
    expect(draftInvoice).toHaveProperty("totalAmount");
    expect(draftInvoice).toHaveProperty("nextInvoiceNumber");
    expect(Array.isArray(draftInvoice.activities)).toBe(true);
  });

  it("should generate invoice from unpaid activities", async () => {
    const db = await getDb();
    if (!db) throw new Error("Database not available");

    // Check if there are unpaid activities first
    const unpaidActivities = await db
      .select()
      .from(videoCallAttendance)
      .where(eq(videoCallAttendance.userId, mockContext.user.id))
      .limit(1);

    if (unpaidActivities.length === 0) {
      console.log("No unpaid activities found for testing - skipping invoice generation test");
      return;
    }

    const caller = autoInvoicesRouter.createCaller(mockContext);
    
    const result = await caller.generateInvoice({
      budgetLineCategory: "delivery",
    });
    
    expect(result).toBeDefined();
    expect(result).toHaveProperty("invoiceId");
    expect(result).toHaveProperty("invoiceNumber");
    expect(result).toHaveProperty("invoiceCode");
    expect(result).toHaveProperty("totalAmount");
    expect(result).toHaveProperty("title");
    expect(result.totalAmount).toBeGreaterThan(0);
    
    // Verify invoice was created in database
    const [invoice] = await db
      .select()
      .from(invoices)
      .where(eq(invoices.id, result.invoiceId))
      .limit(1);
    
    expect(invoice).toBeDefined();
    expect(invoice.status).toBe("pending");
    expect(invoice.autoGenerated).toBe(true);
    expect(invoice.budgetLineCategory).toBe("delivery");
  });

  it("should retrieve invoice history", async () => {
    const caller = autoInvoicesRouter.createCaller(mockContext);
    
    const history = await caller.getInvoiceHistory();
    
    expect(Array.isArray(history)).toBe(true);
    // History may be empty if no invoices have been generated yet
    if (history.length > 0) {
      expect(history[0]).toHaveProperty("id");
      expect(history[0]).toHaveProperty("invoiceNumber");
      expect(history[0]).toHaveProperty("amount");
      expect(history[0]).toHaveProperty("status");
    }
  });
});
